project_id = "uktasyktlthfermkhmwe"

[functions.fetch-news]
verify_jwt = false

[functions.fetch-cnn-news]
verify_jwt = false

[functions.verify-news]
verify_jwt = false

[functions.analyze-link]
verify_jwt = false